name: 'Keploy Cards Action'
description: "A action to run e2e test run"
author: Alphasians
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  workdir:
    description: Relative path under $GITHUB_WORKSPACE where the repository was checked out
    required: false
    default: ${{ github.workspace }}
  delay:
    description: Delay between each test cases
    required: false
    default: 10
    
outputs:
  passed:
    description: Count of passed tests
  failed:
    description: Count of failed tests
  skipped:
    description: Count of skipped tests
  time:
    description: Test execution time [ms]

runs:
  using: "composite"
  steps:
  - name: Setup GITHUB_PATH for script
    run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - name: Check PWD
    run: ls
    shell: bash
  - name: Grant permissions
    run: chmod +x install.sh
    shell: bash
    env:
      ENTITY: ${{ github.action_path }}
      GITHUB_WORKSPACE: ${{ inputs.workdir }}
  - name: Run Script
    run:  install.sh
    shell: bash
    env:
      ENTITY: ${{ github.action_path }}
      GITHUB_WORKSPACE: ${{ inputs.workdir }}
      DELAY: ${{ inputs.delay }}