name: 'Keploy TestRun Report'
description: "A action to run e2e test run"
author: Alphasians
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the repository was checked out
    required: true
  delay:
    description: Delay between each test cases
    required: false
    default: 20
  command:
    description: Command to run the application
    required: true
  keploy-path:
    description: Path to keploy
    required: true
    default: ./
outputs:
  test-report:
    description: Keploy Test report
  success:
    description: Count of passed tests
  failed:
    description: Count of failed tests

runs:
  using: "composite"
  steps:
  - name: Setup GITHUB_PATH for script
    run: |
      echo "${{ github.action_path }}" >> $GITHUB_PATH
      echo "${{ inputs.working-directory }}"
    shell: bash
  - name: Grant permissions
    run: chmod +x ${GITHUB_ACTION_PATH}/install.sh
    shell: sh
  - id: keploy-test-report
    name: Run Script
    run:  |
      ${GITHUB_ACTION_PATH}/install.sh
      echo "$(find /${GITHUB_WORKSPACE}/${WORKDIR}/keploy/ -type d -name 'test-set-*' | wc -l)" > ${GITHUB_WORKSPACE}/${WORKDIR}/testSets.yml
      cd ${GITHUB_WORKSPACE}/${WORKDIR}/keploy/testReports
      ls
      echo "$(find "$@" -type f | wc -l)" > ${GITHUB_WORKSPACE}/${WORKDIR}/testReports.yml
      cat ${GITHUB_WORKSPACE}/${WORKDIR}/testSets.yml      
      cat ${GITHUB_WORKSPACE}/${WORKDIR}/testReports.yml
      for i in $(find "$@" -type f | wc -l)
      do
        echo "Processing $i report.yaml file..."
        echo "${GITHUB_WORKSPACE}/${WORKDIR}/keploy/testReports/report-i.yaml"
      done
    shell: sh
    env:
      WORKDIR: ${{ inputs.working-directory }}
      DELAY: ${{ inputs.delay }}
      COMMAND : ${{ inputs.command }}
      KEPLOY_PATH: ${{inputs.keploy-path}}
  - name: Upload TestReport
    uses: actions/upload-artifact@v3
    with:
        name: keploy-test-report-summary
        path: ${GITHUB_WORKSPACE}/${WORKDIR}/keploy/testReports/report-*.yaml
