name: 'Vaunt Cards Action'
description: 'Action to generate vaunt cards in the .vaunt/cards directory'
author: VauntDev
branding:
  icon: 'rabbit'
  color: 'orange'

inputs:
  workdir:
    description: Relative path under $GITHUB_WORKSPACE where the repository was checked out
    required: false
  delay:
    description: Delay between each test cases
    required: false
    default: 10
    
outputs:
  passed:
    description: Count of passed tests
  failed:
    description: Count of failed tests
  skipped:
    description: Count of skipped tests
  time:
    description: Test execution time [ms]

runs:
  using: "composite"
  steps:
  - name: Setup GITHUB_PATH for script
    run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - name: Run script
    run: | 
      chmod +x ./install.sh
      install.sh
    shell: bash
    env:
      ENTITY: ${{ github.repository_owner }}
      GITHUB_WORKSPACE: ${{ inputs.workdir }}
      DELAY: ${{ inputs.delay }}