name: 'Keploy TestRun'
description: "A action to run e2e test run"
author: Alphasians
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the repository was checked out
    required: true
  delay:
    description: Delay between each test cases
    required: false
    default: 20
  command:
    description: Command to run the application
    required: true
  keploy-path:
    description: Path to keploy
    required: true
    default: /

runs:
  using: "composite"
  steps:
  - name: Setup GITHUB_PATH for script
    run: |
      echo "${{ github.action_path }}" >> $GITHUB_PATH
      echo "${{ inputs.working-directory }}"
    shell: bash
  - name: Grant permissions
    run: chmod +x ${GITHUB_ACTION_PATH}/install.sh
    shell: sh
  - name: Run Script
    run:  ${GITHUB_ACTION_PATH}/install.sh
    shell: sh
    env:
      WORKDIR: ${{ inputs.working-directory }}
      DELAY: ${{ inputs.delay }}
      COMMAND : ${{ inputs.command }}
      KEPLOY_PATH: ${{inputes.keploy-path}}
