name: Keploy Test Report
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Keploy Cards
      uses: alphasians/test-reportql@main